Repository opsmonsters/quick-bite, pull requests merged in 2025-01, with the labels that each got.

#18 #339-/-PASSWORD API MODIFIED
  out/production/resources/application.properties
  src/main/java/com/opsmonsters/quick_bite/Configurations/SecurityFilter.java
  src/main/java/com/opsmonsters/quick_bite/controller/AuthController.java
  src/main/java/com/opsmonsters/quick_bite/controller/UserController.java
  src/main/java/com/opsmonsters/quick_bite/dto/ForgotPasswordDto.java
  src/main/java/com/opsmonsters/quick_bite/dto/ResetPasswordDto.java
  src/main/java/com/opsmonsters/quick_bite/dto/UserDto.java
  src/main/java/com/opsmonsters/quick_bite/models/Users.java
  src/main/java/com/opsmonsters/quick_bite/repositories/UserRepo.java
  src/main/java/com/opsmonsters/quick_bite/services/JwtServices.java
  src/main/java/com/opsmonsters/quick_bite/services/UserService.java
  src/main/java/com/opsmonsters/quick_bite/services/UserServices.java
  src/main/resources/application.properties
Labels: MERGE

#24 #358-Saved all DB vars in ENV
  src/main/resources/application.properties
Labels: REVIEW REQUIRED

#25 resolved conflicts
  src/main/java/com/opsmonsters/quick_bite/services/OtpService.java
Labels: MERGE

#23 #355-empty constructor removed-user DTO// Accessibility updated in security filter
  src/main/java/com/opsmonsters/quick_bite/Configurations/JwtAuthenticationFilter.java
Labels: MERGE, CHANGES UPDATED
